### ISSUE TITLE
Browser page crashed

### ISSUE THREAD

**Issue by jgournet** [grafana/grafana-image-renderer#229]
**What happened**:
1) overall setup is working well: image renderer works and sends nice images to slack.
2) Then, "something" happens, and from there on, image-renderer keeps on crashing. A pod restart solves the issue for any time between a few hours and 2 weeks.
Logs, including 1 successfull call  at the top (just to show that it does work fine)
```
 2021-05-18T22:26:33.755623434Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:26:33 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=QAWfFera3MASlHo2K9CsSfU76HXIMt74&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" 200 33110 \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:26:33.755729023Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:31:27.805524963Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:31:31.096108470Z {"file":"/tmp/9ef11c5d.png","level":"debug","message":"Deleting temporary file"}
 2021-05-18T22:31:31.096358221Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:31:31 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=8760Dc4XtE6mw5ModH8Ni2gvA3BsA60M&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" 200 35856 \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:31:31.096447478Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:32:01.812452652Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:32:01.893723534Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=28&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:32:04.883703062Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:32:16.809733713Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:32:16.810404284Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:32:16 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=swkT9o7zVkQqY3KrjnWZzJXswURm5baN&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F245f6eb185f8ac33ccace621ffa78b3d5f7168c7%2Fpm-initializer-integration-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:32:16.888323005Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=28&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:32:16.888795363Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:32:16 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=AMb767hooNw0xb901byUSpqDepO0hMXT&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F245f6eb185f8ac33ccace621ffa78b3d5f7168c7%2Fpm-initializer-integration-production%3ForgId%3D1%26panelId%3D28%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:32:17.908651634Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=swkT9o7zVkQqY3KrjnWZzJXswURm5baN&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F245f6eb185f8ac33ccace621ffa78b3d5f7168c7%2Fpm-initializer-integration-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:34:11.806590238Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:34:15.084875325Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:34:26.803764943Z {"url":"http://localhost:3000/d-solo/245f6eb185f8ac33ccace621ffa78b3d5f7168c7/pm-initializer-integration-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:34:26.804331979Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:34:26 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=mQFuAxOQNrkOpEuzTF25mLpurBk227Na&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F245f6eb185f8ac33ccace621ffa78b3d5f7168c7%2Fpm-initializer-integration-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:34:28.387807137Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=mQFuAxOQNrkOpEuzTF25mLpurBk227Na&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F245f6eb185f8ac33ccace621ffa78b3d5f7168c7%2Fpm-initializer-integration-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:40:15.890497352Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:40:16.881013187Z {"url":"http://localhost:3000/d-solo/4uoyVOWMk/pod-container-alerts?orgId=1&panelId=8&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:40:18.942108149Z (node:6) UnhandledPromiseRejectionWarning: Error: Page crashed!
 2021-05-18T22:40:18.942140068Z     at Page._onTargetCrashed (/usr/src/app/node_modules/puppeteer/lib/Page.js:209:28)
 2021-05-18T22:40:18.942146488Z     at CDPSession.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/Page.js:129:57)
 2021-05-18T22:40:18.942150902Z     at CDPSession.emit (events.js:315:20)
 2021-05-18T22:40:18.942154045Z     at CDPSession._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:166:18)
 2021-05-18T22:40:18.942157338Z     at Connection._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:83:25)
 2021-05-18T22:40:18.942160645Z     at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
 2021-05-18T22:40:18.942164072Z     at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:132:16)
 2021-05-18T22:40:18.942166940Z     at WebSocket.emit (events.js:315:20)
 2021-05-18T22:40:18.942170077Z     at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:835:20)
 2021-05-18T22:40:18.942173014Z     at Receiver.emit (events.js:315:20)
 2021-05-18T22:40:18.942284038Z (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
 2021-05-18T22:40:23.986605989Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:40:30.886978712Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:40:30.887584790Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:40:30 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=tbDQgnUneD9mHGv8aCRTQ3481OO31s0q&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:40:31.823169971Z {"url":"http://localhost:3000/d-solo/4uoyVOWMk/pod-container-alerts?orgId=1&panelId=8&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:40:31.823587714Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:40:31 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=57gnMY0Y8s0PuJHKz6nLpEGrlROrKbvG&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4uoyVOWMk%2Fpod-container-alerts%3ForgId%3D1%26panelId%3D8%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:40:37.002166714Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=57gnMY0Y8s0PuJHKz6nLpEGrlROrKbvG&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4uoyVOWMk%2Fpod-container-alerts%3ForgId%3D1%26panelId%3D8%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:41:21.805340266Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:41:23.983682105Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:41:36.802288068Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:41:36.802720548Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:41:36 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=iwLtTDdgUYu6OHE0uy9y2xj63ROJBUj8&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:41:37.437403076Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=iwLtTDdgUYu6OHE0uy9y2xj63ROJBUj8&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:44:04.806177231Z {"url":"http://localhost:3000/d-solo/4uoyVOWMk/pod-container-alerts?orgId=1&panelId=8&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:44:07.182613587Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:44:19.803106962Z {"url":"http://localhost:3000/d-solo/4uoyVOWMk/pod-container-alerts?orgId=1&panelId=8&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:44:19.803643659Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:44:19 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=AlbSZe0twKi0xJWpAa23grVatDpl2iYG&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4uoyVOWMk%2Fpod-container-alerts%3ForgId%3D1%26panelId%3D8%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:44:20.422507056Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=AlbSZe0twKi0xJWpAa23grVatDpl2iYG&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4uoyVOWMk%2Fpod-container-alerts%3ForgId%3D1%26panelId%3D8%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:45:12.911815863Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:45:15.096438484Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:45:27.908590870Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:45:27.908900410Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:45:27 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=gwF4unsyneEDM1soPTMKfB4sB0uTWfX1&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:45:28.520988010Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=gwF4unsyneEDM1soPTMKfB4sB0uTWfX1&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:52:21.806305091Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:52:23.884499532Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
 2021-05-18T22:52:36.799639058Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Connection closed"}
 2021-05-18T22:52:36.800045288Z {"message":"::ffff:127.0.0.1 - - [18/May/2021:22:52:36 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=EVY2ULNZs1JOgJk2LKQp1foCroMCB7XR&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.1.5\"\n","level":"debug"}
 2021-05-18T22:52:37.518247053Z {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=EVY2ULNZs1JOgJk2LKQp1foCroMCB7XR&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F63dae39ae810539b3108233c3749bf114998da82%2Fsbr2-compliance-production%3ForgId%3D1%26panelId%3D29%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 15000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:171:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error","message":"Request failed"}
 2021-05-18T22:56:12.895149535Z {"url":"http://localhost:3000/d-solo/63dae39ae810539b3108233c3749bf114998da82/sbr2-compliance-production?orgId=1&panelId=29&render=1","level":"debug","message":"Render request received"}
 2021-05-18T22:56:14.883797569Z {"error":"Error: Page crashed!","level":"error","message":"Browser page crashed"}
```

**What you expected to happen**:
not crash :)

**How to reproduce it (as minimally and precisely as possible)**:
I honestly don't know ...

**Anything else we need to know?**:
Mem & CPU usage at that time (logs are in UTC, while screenshot is in UTC+10).
![image](https://user-images.githubusercontent.com/54783141/118750841-9988ee00-b8a3-11eb-876e-3e4bfb595fd9.png)
This shows some high CPU usage (looks like there were failures at that time as well), then a manual restart of the pod at 9:25, and the pod going through the roof again (and having the same suite of errors)

**Environment**:
- Grafana Image Renderer version: "grafana/grafana-image-renderer:latest"
- Grafana version: 7.1.5
- Installed plugin or remote renderer service: ?
- OS Grafana Image Renderer is installed on: kubernetes AWS EKS 1.19
- User OS & Browser: not relevant
- Others: installed via this manifest, on top of grafana installed via rancher charts ( https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-monitoring/rancher-monitoring/9.4.203 )
```
spec:
  template:
    spec:
      containers:
      - image: grafana/grafana-image-renderer:latest
        imagePullPolicy: IfNotPresent
        name: grafana-image-renderer
        ports:
        - containerPort: 8081
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 256Mi
```

**Comment by jgournet** [comment]
ps -ef command result:
```
/usr/src/app $ ps -ef
PID   USER     TIME  COMMAND
    1 472       0:00 dumb-init -- node build/app.js server --config=config.json
    6 472       0:03 node build/app.js server --config=config.json
 1306 472      21:50 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 1310 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 1311 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 1365 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=7146016762517841554,10703166498941563101,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-b
 2399 472       2:49 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 2403 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 2404 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 2459 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=13925908151472710199,906851974963561010,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 2808 472       0:56 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 2812 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 2813 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 2871 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=6714129179673735007,17099834667523999963,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-b
 3016 472       1:24 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3020 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3021 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3077 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=14270388620581758672,422427405984375005,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 3163 472       0:59 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3167 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3168 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3283 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=12832549795395199117,14510046914754411558,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-
 3363 472       1:24 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3367 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3368 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3424 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=9528702974541555516,9035325658865604278,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 3431 472       1:17 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3435 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3436 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3493 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=59791321053581787,6819457603873824521,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-brea
 3500 472       1:04 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3504 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3505 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3562 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=3740860523921336713,5393524573057275017,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 3574 472       0:49 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3578 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3579 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3636 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=1419543293350128004,9273328243895367621,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 3725 472       1:10 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3729 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3730 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3778 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=10484760584669899906,15860650112859342700,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-
 3792 472       1:07 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3796 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3797 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 3853 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=5525854386003521039,7254172238287209762,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-br
 3944 472       0:51 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 3948 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 3949 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 4004 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=6060671945329723967,15596482156771773220,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-b
 4094 472       0:50 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-
 4098 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
 4099 472       0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --headless --headless
 4118 472       1:24 /usr/lib/chromium/chrome --type=renderer --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --force-color-profile=srgb --remote-debugging-port=0 --allow-pre-commit-input --ozone-platform
 4124 472       1:23 /usr/lib/chromium/chrome --type=renderer --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --force-color-profile=srgb --remote-debugging-port=0 --allow-pre-commit-input --ozone-platform
 4156 472       0:00 /usr/lib/chromium/chrome --type=gpu-process --field-trial-handle=18317130642246438140,9545137052642238306,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-b
 4306 472       0:00 sh
 4319 472       0:00 ps -ef
```

**Comment by Legion2** [comment]
We also have this problem. The image renderer worked fine for the last months, but suddenly stopped rendering the images and have a high cpu utilization after the errors. We installed grafana and the image renderer with the Grafana Helm chart. Because of the continuously high CPU utilization we disabled the image renderer.

![image](https://user-images.githubusercontent.com/12752323/119219766-6b93eb80-bae7-11eb-89b0-8e8084991fdd.png)
![image](https://user-images.githubusercontent.com/12752323/119219781-85353300-bae7-11eb-88ae-8d564be16312.png)

Memory limit is set to 500Mi and upon reaching this limit, the cpu utilization dropped below 1.

Historic CPU Usage, staring from 2021-05-14 the errors happened and the cpu utilization increased:
![image](https://user-images.githubusercontent.com/12752323/119219860-ef4dd800-bae7-11eb-830d-e77ca261a8b0.png)


Grafana Helm Chart version: 6.9.1
Grafana version: 7.5.5

**Comment by jgournet** [comment]
quick update: I did upgrade the memory limit from 768M to 2G: renderer worked almost 5days before crashing again (up from a few hours).
(not sure if it's repeatable yet :) )

**Comment by Bujupah** [comment]
This may help https://github.com/puppeteer/puppeteer/issues/1321

**Comment by jgournet** [comment]
> This may help [puppeteer/puppeteer#1321](https://github.com/puppeteer/puppeteer/issues/1321)
> 
> Also I think you need to increase request cpu to 512 and ram to 1gb and adapt the changes to your limits...
> but before doing that check your config.json
> there is concurrent_render mode and limit options there, I suggest you to check it
> 
> https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit

Thanks - that's indeed interesting ! 
a few notes:
1) what's the difference between https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit
 and https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit ? (ie: which one overrides the other ?)
in doubt, going to decrease both to 2 and see what happens

2) Not sure how accurate that is, but here's the FS size while it's crashing:
```
/usr/src/app $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  40.0G      6.7G     33.3G  17% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.7G         0      3.7G   0% /sys/fs/cgroup
/dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /dev/termination-log
/dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/resolv.conf
/dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/hostname
/dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     3.7G     12.0K      3.7G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.7G         0      3.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.7G         0      3.7G   0% /sys/firmware
```
=> /dev/shm is empty

3) I've already raised the CPU+MEM limits and requests. It seemed like it helped at first (renderer did not crash for 3 days), but then it crashed twice in 24h... so not super sure of the impact of that

**Comment by Bujupah** [comment]
> > This may help [puppeteer/puppeteer#1321](https://github.com/puppeteer/puppeteer/issues/1321)
> > Also I think you need to increase request cpu to 512 and ram to 1gb and adapt the changes to your limits...
> > but before doing that check your config.json
> > there is concurrent_render mode and limit options there, I suggest you to check it
> > https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit
> 
> Thanks - that's indeed interesting !
> a few notes:
> 
> 1. what's the difference between https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit
>    and https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit ? (ie: which one overrides the other ?)
>    in doubt, going to decrease both to 2 and see what happens
> 2. Not sure how accurate that is, but here's the FS size while it's crashing:
> 
> ```
> /usr/src/app $ df -h
> Filesystem                Size      Used Available Use% Mounted on
> overlay                  40.0G      6.7G     33.3G  17% /
> tmpfs                    64.0M         0     64.0M   0% /dev
> tmpfs                     3.7G         0      3.7G   0% /sys/fs/cgroup
> /dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /dev/termination-log
> /dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/resolv.conf
> /dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/hostname
> /dev/nvme0n1p1           40.0G      6.7G     33.3G  17% /etc/hosts
> shm                      64.0M         0     64.0M   0% /dev/shm
> tmpfs                     3.7G     12.0K      3.7G   0% /run/secrets/kubernetes.io/serviceaccount
> tmpfs                     3.7G         0      3.7G   0% /proc/acpi
> tmpfs                    64.0M         0     64.0M   0% /proc/kcore
> tmpfs                    64.0M         0     64.0M   0% /proc/keys
> tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
> tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
> tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
> tmpfs                     3.7G         0      3.7G   0% /sys/firmware
> ```
> 
> => /dev/shm is empty
> 
> 1. I've already raised the CPU+MEM limits and requests. It seemed like it helped at first (renderer did not crash for 3 days), but then it crashed twice in 24h... so not super sure of the impact of that
> 
> Note: thanks again for the suggestions and help

Not sure what you're comparing, but I forget to mention that cluster_limit only works when you're RENDERING_MODE=clustered
https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md

And yeah that's actually weird how it crashs but I am sure this is related to memory, can you share renderer log ?

**Comment by jgournet** [comment]
For the comparison, sorry: managed to do a failed copy/paste:
https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_request_limit
vs 
https://grafana.com/docs/grafana/latest/administration/configuration/#concurrent_render_limit

(I've edited my post now)

as for the logs: there's nothing more than those I posted at the top :/

**Comment by Bujupah** [comment]
Both are same but one is used in Alerting which is concurrent_render_request_limit

And the other is used for panel rendering if you're going to use it's API for other purposes...

That's my guess, I am not sure...

**Comment by Legion2** [comment]
Is there a way to configure a total render limit, so that the image renderer never has to concurrently render more requests than the total limit?

**Comment by Bujupah** [comment]
@Legion2  
Yes you can!
Its either you change your grafana config file or renderer config file or use environment variables...
- Grafana ini file for remote renderer
```ini
[rendering]
concurrent_render_request_limit = 30
```

- Grafana ini file for plugin renderer
```ini
[plugin.grafana-image-renderer]
rendering_clustering_max_concurrency =
```

- Environment variables: 
```ini
RENDERING_MODE=clustered
RENDERING_CLUSTERING_MODE=default
RENDERING_CLUSTERING_MAX_CONCURRENCY=5
```

- Renderer config file
```json
{
...
   "rendering": {
     ...
      "clustering": {     
         ...
         "maxConcurrency":  5
       },
      ...
   }
...
}
```

**Comment by Legion2** [comment]
I set `[rendering] concurrent_render_request_limit` and `[alerting] concurrent_render_limit` to 1 and now it doesn't produce any images anymore. The following is logged in grafana:

```
{"log":"t=2021-06-01T08:31:04+0000 lvl=info msg=\"Sending telegram notification\" logger=alerting.notifier.telegram chat_id=*** bot_token=*** apiAction=sendMessage\n","stream":"stdout","time":"2021-06-01T08:31:04.680429909Z"}
{"log":"t=2021-06-01T08:31:04+0000 lvl=warn msg=\"Failed to close file\" logger=rendering renderer=http path=/var/lib/grafana/png/9u9sesVKny10q4kiIzll.png err=\"close /var/lib/grafana/png/9u9sesVKny10q4kiIzll.png: file already closed\"\n","stream":"stdout","time":"2021-06-01T08:31:04.671664996Z"}
{"log":"t=2021-06-01T08:31:01+0000 lvl=info msg=Rendering logger=rendering renderer=http path=\"d-solo/k1OUIemMz/voize-analytics?orgId=1\u0026panelId=26\"\n","stream":"stdout","time":"2021-06-01T08:31:01.274174223Z"}
{"log":"t=2021-06-01T08:31:01+0000 lvl=info msg=\"New state change\" logger=alerting.resultHandler ruleId=1 newState=alerting prev state=pending\n","stream":"stdout","time":"2021-06-01T08:31:01.257717016Z"}
```

**Comment by AgnesToulet** [comment]
Hello! I noticed a similar behavior while doing some load testing of the application: high CPU and memory slowy going to the roof too after the tests were finished. In my case, I narrowed down the issue to the [`newPage`](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L169) function that was (for some requests) hanging forever, preventing the browser to be closed and causing these issues. I fixed this by updating the plugin config file and adding the `--disable-gpu` flag to the Chromium args:
```
{
  ...
  "rendering": {
    ...
    "args": [
      "--no-sandbox",
      "--disable-gpu"
    ],
    ...
  }
}
```
Could you try it out to see if your issue has the same root cause or another please?

@Legion2 About your last comment, I did a quick test with these settings and it seems like everything worked fine. Are you able to tell if that could be related to the first issue here? For information, the warning log `Failed to close file` is not an issue here; we fixed trying to close a file that is already closed in the renderer service in Grafana 8.0.

**Comment by Legion2** [comment]
I'm using the grafana helm chart, to deploy grafana and the image renderer. So I cannot edit the config.json. Is it possible to override the rendering args using environment variables?

**Comment by jgournet** [comment]
Note:
while adding that option (not so easy in our setup), I realized that image renderer has not crashed in a long while.
Either:
- setting ALERTING_CONCURRENT_RENDER_LIMIT and RENDERING_CONCURRENT_RENDER_REQUEST_LIMIT to 2 solved it (although I'm pretty sure I had crashes after adding those options)
- or somehow image renderer was updated and it was fixed (we use "latest" image)
- or since we worked on decreasing the number of alerts (we were getting too many of them), that fixed it

either way: thanks @AgnesToulet  for checking this issue - and sorry I can't test your fix

**Comment by AgnesToulet** [comment]
@Legion2 Yes it's possible, the env variable is `RENDERING_ARGS`

@jgournet I think it's your first or third point that helped. I'm doing my tests with latest and having the same issue. But I'm doing load testing so sending 10 concurrent requests during 15 minutes and it's what caused the issue. 

Also, it happens only with the `default` rendering mode not with the `clustered` one. See section "Change how browser instances are created:" from this page: https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables for more details on the difference between rendering modes.

**Comment by jgournet** [comment]
Thanks @AgnesToulet for creating that pull request, as the issue came back for us :/
Can't wait for this to be merged ...

**Comment by jgournet** [comment]
@AgnesToulet : any chance your PR can get merged ?
