### ISSUE TITLE
v3.9.0 Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by giuliomagnifico** [grafana/grafana-image-renderer#486]
**What happened**:
After the update, and after I built from source there are some issue with puppeteer, since the browser is not able to render

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Just launch a render

**Anything else we need to know?**:

The bug error:

```
Dec 06 13:19:13 Grafana systemd[1]: Started Grafana-image-renderer.Dec 06 13:19:17 Grafana node[6448]: {"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}Dec 06 13:19:18 Grafana node[6448]: {"level":"error","message":"Request failed","stack":"Error: Failed to launch the browser process!\n/root/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome: 3: Syntax error: \")\" unexpected\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n\n    at Interface.onClose (/root/grafana-image-renderer/node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)\n    at Interface.emit (node:events:526:35)\n    at Interface.close (node:internal/readline/interface:533:10)\n    at Socket.onend (node:internal/readline/interface:259:10)\n    at Socket.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","url":"/render?deviceScaleFactor=2.000000&domain=192.168.1.6&encoding=&height=1850&renderKey=DU0PyFqz1pqVaXcDQgoFKywSq9PZWaFe&timeout=60&timezone=&url=http%3A%2F%2F192.168.1.6%3A3001%2Fd%2FFGioSdO4z31%2Fcasetta%3Fwidth%3D1600%26height%3D1850%26kiosk%3Dtv%26scale%3D2%26theme%3Ddark%26from%3Dnow-24h%26to%3Dnow%26var-ISP%3DTelecom%2520Italia%26render%3D1&width=1600"}
Dec 06 13:19:18 Grafana node[6448]: {"level":"error","message":"::ffff:192.168.1.6 - - [06/Dec/2023:12:19:18 +0000] \"GET /render?deviceScaleFactor=2.000000&domain=
192.168.1.6&encoding=&height=1850&renderKey=DU0PyFqz1pqVaXcDQgoFKywSq9PZWaFe&timeout=60&timezone=&url=http%3A%2F%2F192.168.1.6%3A3001%2Fd%2FFGioSdO4z31%2Fcasetta%3F
width%3D1600%26height%3D1850%26kiosk%3Dtv%26scale%3D2%26theme%3Ddark%26from%3Dnow-24h%26to%3Dnow%26var-ISP%3DTelecom%2520Italia%26render%3D1&width=1600 HTTP/1.1\" 5
00 96 \"-\" \"Grafana/10.2.2\"\n"}
```

When I run `yarn install --pure-lockfile`

I got this dependency issue:

`poolpeteer@0.23.3" has incorrect peer dependency "puppeteer@^13.1.1".`

**Environment**:
- Grafana Image Renderer version: 3.9.0
- Grafana version: 10.2.2
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on: Raspberry PI
- User OS & Browser:
- Others:

**Comment by siccl** [comment]
I get the same error on 
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-169-generic x86_64)

I fixed this, creating a symbolink link :
/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux -> /var/lib/grafana/plugins/grafana-image-renderer/chrome/linux-121.0.6156.2/chrome-linux64

**Comment by giuliomagnifico** [comment]
Thanks for the reply, by the way I have compiled the _grafana-image-renderer_ from source, so I don't have the folders you have.

By the way I fixed this error days ago simply by updating puppeteer and re-compiling _grafana-image-renderer_

`npm install puppeteer@^13.1.1`

Then 

`yarn install && yarn run build`

Now it works again.

 Hope this help someone!

**Comment by khushijain21** [comment]
I have the same issue, it is not resolved with above solutions

**Comment by giuliomagnifico** [comment]
> I have the same issue, it is not resolved with above solutions

Yes I can confirm, and I also updated puppeteer:

`npm install puppeteer@latest`

but grafana-imager-render still not works.
