### ISSUE TITLE
Image Renderer Fails with Timeout & Retries on 60s Interval w/ InfluxDB Datasources

### ISSUE THREAD

**Issue by nharper-usgs** [grafana/grafana-image-renderer#785]
**What happened**:
I have recently setup the docker version of the grafana image renderer. This docker service is a part of a larger compose setup that includes both InfluxDB and Grafana. I have the services talking to eachother and can successfully download images via curl and other methods. 

However, I am seeing pretty sporadic latency issues that I believe I've traced back to the renderer retrying after an initial failed network request. 

More often than not, I am able to download the images in about ~2s, however, every 2-5 requests, the images take _exactly_ ~61-62s. 

`
(base) [user@server grafana]$ curl -L "http://[URL]" -o tmp.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52310  100 52310    0     0  31474      0  0:00:01  0:00:01 --:--:-- 31474
(base) [user@server grafana]$ curl -L "http://[URL]" -o tmp.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11196  100 11196    0     0   6397      0  0:00:01  0:00:01 --:--:--  6401
(base) [user@server grafana]$ curl -L "http://[URL]t" -o tmp.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11187  100 11187    0     0    181      0  0:01:01  0:01:01 --:--:--  3199
(base) [user@server grafana]$ curl -L "http://admin:admin@localhost:3001/render/d-solo/cemi669r5v5s0f?orgId=1&from=now()&to=now()-1m&var-Drainages=Carbon&panelId=panel-67&&width=400&height=300&tz=UTC&theme=light" -o tmp.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10246  100 10246    0     0    165      0  0:01:02  0:01:01  0:00:01  2180
`

In the renderer logs, I get the following _only when I experience the 60s+ requests_

`
renderer  | {"failure":"net::ERR_ABORTED","level":"error","message":"Browser request failed","method":"POST","url":"http://grafana:3000/api/ds/query?ds_type=influxdb&requestId=SQR100"}
renderer  | {"err":"TimeoutError: Waiting failed: 60000ms exceeded\n    at new WaitTask (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50:34)\n    at IsolatedWorld.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Realm.js:25:26)\n    at CdpFrame.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:561:43)\n    at CdpFrame.<anonymous> (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)\n    at CdpPage.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:1366:37)\n    at waitForQueriesAndVisualizations (/home/nonroot/build/browser/browser.js:595:16)\n    at /home/nonroot/build/browser/browser.js:375:19\n    at callback (/home/nonroot/build/browser/browser.js:546:34)\n    at ClusteredBrowser.withMonitoring (/home/nonroot/build/browser/browser.js:553:16)\n    at ClusteredBrowser.performStep (/home/nonroot/build/browser/browser.js:509:36)","level":"error","message":"Error while performing step","step":"panelsRendered","url":"http://grafana:3000/d-solo/[URL....]"}
`

The reason I think there is a retry involved is because I always successfully download the image after the 60s timeout happens. 

**What you expected to happen**:
I'd expect consistent download times. 

**How to reproduce it (as minimally and precisely as possible)**:
I simply retry the same image renderering requests. 

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest (4.x.x+)
- Grafana version: latest (12.x.x+)
- Installed plugin or remote renderer service: remote
- OS Grafana Image Renderer is installed on: default docker OS
- User OS & Browser: RHEL
- Others: I've included the compose setup below for grafana and renderer

`
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    shm_size: 1g
    environment: 
      - AUTH_TOKEN=test-token
      - RENDERING_MODE=clustered
      - RENDERING_CLUSTERING_TIMEOUT=600
      - RENDERING_VIEWPORT_MAX_WIDTH=3000
      - RENDERING_VIEWPORT_MAX_HEIGHT=3000
      - ENABLE_METRICS=true
      - RENDERING_TIMING_METRICS=true
      # Try timeout
      - LOG_LEVEL=debug
    ports:
      - "8081:8081"
    networks: 
      - test_network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=test
      - GF_SECURITY_ADMIN_PASSWORD=test
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_ROOT_URL=http://grafana:3000/
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_RENDERER_TOKEN=test-token
      - GF_RENDERING_RENDERING_TIMEOUT=30
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      - renderer
    networks:
      - test_network
`

**Comment by nharper-usgs** [comment]
Update: I've confirmed that grafana is failing its initial attempt to query influx and that correlates with the delayed renders... though I'm not entirely sure why, but I believe I have the following happen: 
1. Renderer Queries Grafana
2. Grafana Queries Influxdb
3. Influxdb returns a "context cancelled" error. 
4. Renderer waits 60s to retry. 

While I'm not sure if the context cancelled error is influx or grafana, I think a quick fix for this would be to include an env_var to decrease the renderer's retry mechanism.

**Comment by MansuyDavid** [comment]
I have the same error.

### Environment
docker running 3 containers on the same server :
grafana-enterprise
grafana-image-renderer
prometheus

grafana-enterprise and grafana renderer share a docker network to communicate directly.

when i have upgraded grafana from 12.0.0 to 12.3.0 I start to have this error, that i had not on 12.0.0.
i updates the image-renderer to latest version to try (4.1.2) with no changes.

### Details
I found the same error in image-renderer container : 
```
* during step "navigate"
* after loading majority of the dashboard variables with http://grafana:3000/api/datasources/uid/deebkmjyon9j4d/resources/api/v1/label/space_limit/values? ....
* renderer begin to send "POST" messages like 
{"level":"debug","message":"Browser request","method":"POST","url":"http://grafana:3000/api/ds/query?ds_type=prometheus&requestId=SQR100"}
{"failure":"net::ERR_ABORTED","level":"error","message":"Browser request failed","method":"POST","url":"http://grafana:3000/api/ds/query?ds_type=prometheus&requestId=SQR100"}
{"level":"debug","message":"Step ends","step":"navigate","url":"http://grafana:3000/d-solo/oracle4ever?....."}
{"level":"debug","message":"Step begins","step":"panelsRendered","url":"http://grafana:3000/d-solo/oracle4ever?....."}
{"level":"debug","message":"Waiting for dashboard/panel to load","timeout":"60s"}
{"err":"TimeoutError: Waiting failed: 60000ms exceeded\n    at new WaitTask (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50:34)\n    at IsolatedWorld.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Realm.js:25:26)\n    at CdpFrame.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:561:43)\n    at CdpFrame.<anonymous> (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)\n    at CdpPage.waitForFunction (/home/nonroot/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:1366:37)\n    at waitForQueriesAndVisualizations (/home/nonroot/build/browser/browser.js:601:16)\n    at /home/nonroot/build/browser/browser.js:380:19\n    at callback (/home/nonroot/build/browser/browser.js:552:34)\n    at Browser.withMonitoring (/home/nonroot/build/browser/browser.js:559:16)\n    at Browser.performStep (/home/nonroot/build/browser/browser.js:515:36)","level":"error","message":"Error while performing step","step":"panelsRendered","url":"http://grafana:3000/d-solo/oracle4ever?....."}
then the step "screenshot" begin end end with success and image is generated.

````

on grafana container i had this : 
```
* loading of dashboard variables via logger=tsdb.prometheus endpoint=callResource pluginId=prometheus dsName=Prometheus dsUID=deebkmjyon9j4d uname=dematic t=2025-10-27T15:21:26.66300087Z level=debug msg="Sending resource query" URL="api/v1/label/space_limit/values?...."
logger=query_data t=2025-10-27T15:21:26.677891463Z level=debug msg="Processed metrics query" ref_id="ALL TBS" from=1756684800000 to=1759276799000 interval=3600000 max_data_points=900 query="{\"datasource\":{\"type\":\"prometheus\",\"uid\":\"deebkmjyon9j4d\"},\"datasourceId\":1,\"editorMode\":\"code\",\"exemplar\":false,\"expr\":\".....\"}\",\"format\":\"time_series\",\"hide\":false,\"instant\":false,\"interval\":\"\",\"intervalMs\":3600000,\"legendFormat\":\"{{customer_id}}:{{server_name}}:{{database_name}}=\\u003e {{tablespace_name}}\",\"maxDataPoints\":900,\"range\":true,\"refId\":\"ALL TBS\",\"requestId\":\"62ALL TBS\",\"utcOffsetSec\":0}"
logger=query_data t=2025-10-27T15:21:26.677912478Z level=debug msg="Processed metrics query" ref_id=SUM from=1756684800000 to=1759276799000 interval=3600000 max_data_points=900 query="{\"datasource\":{\"type\":\"prometheus\",\"uid\":\"deebkmjyon9j4d\"},\"datasourceId\":1,\"editorMode\":\"code\",\"exemplar\":false,\"expr\":\".....\",\"hide\":false,\"instant\":false,\"interval\":\"\",\"intervalMs\":3600000,\"legendFormat\":\"{{customer_id}}:{{server_name}}:{{database_name}}=\\u003e Total size DB without TMP/UNDO\",\"maxDataPoints\":900,\"range\":true,\"refId\":\"SUM\",\"requestId\":\"62SUM\",\"utcOffsetSec\":0}"
logger=query_data t=2025-10-27T15:21:26.677924312Z level=debug msg="Processed metrics query" ref_id=A from=1756684800000 to=1759276799000 interval=3600000 max_data_points=900 query="{\"datasource\":{\"type\":\"prometheus\",\"uid\":\"deebkmjyon9j4d\"},\"datasourceId\":1,\"editorMode\":\"code\",\"exemplar\":false,\"expr\":\".....\",\"hide\":false,\"instant\":false,\"interval\":\"\",\"intervalMs\":3600000,\"legendFormat\":\"{{customer_id}}:{{server_name}}:{{database_name}}=\\u003e Total size DB\",\"maxDataPoints\":900,\"range\":true,\"refId\":\"A\",\"requestId\":\"62A\",\"utcOffsetSec\":0}"
* this 3 lines seems to be the "POST" of SQR100
logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=Prometheus dsUID=deebkmjyon9j4d uname=d... t=2025-10-27T15:21:26.704153849Z level=debug msg="Begin query execution" fromAlert=false
logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=Prometheus dsUID=deebkmjyon9j4d uname=d... t=2025-10-27T15:21:26.704233693Z level=debug msg="Sending query" start=2025-09-01T00:00:00Z end=2025-09-30T23:59:59Z step=1h0m0s query="....."
logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=Prometheus dsUID=deebkmjyon9j4d uname=d... t=2025-10-27T15:21:26.704833032Z level=debug msg="Sending query" start=2025-09-01T00:00:00Z end=2025-09-30T23:59:59Z step=1h0m0s query="....."
logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=Prometheus dsUID=deebkmjyon9j4d uname=d... t=2025-10-27T15:21:26.705188159Z level=debug msg="Sending query" start=2025-09-01T00:00:00Z end=2025-09-30T23:59:59Z step=1h0m0s query="....."
logger=context userId=2 orgId=1 uname=dematic t=2025-10-27T15:21:26.714131307Z level=error msg="Error writing to response" err="write tcp 192.168.32.2:3000->192.168.32.3:38748: write: broken pipe"
* 192.168.32.2 is grafana container, 192.168.32.3 is image-renderer container.
logger=context userId=2 orgId=1 uname=d..... t=2025-10-27T15:21:26.714200646Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=192.168.32.3 time_ms=13 duration=13.39792ms size=7913 referer="http://grafana:3000/d-solo/oracle4ever?....." handler=/api/ds/query status_source=downstream
* this seems to be the answer to the post of renderer
```

### things to notice 
- i generate one image for each panel in one dashboard. each time with a "curl" request. always on the previous month, so data are the same at each rendering.
- panels are quite simple, type time series, between 1 and 3 curves
- some panels never have issue, they seems to be immune. (it seems to be the ones that are "repeated" in a separate "row" of the dashboard)
- other pannels have the issue around 50 to 75% of times. but it's random.
- dashboard variable's graph of dependency is not KISS.


I hope this analysis will help you to pinpoint the issue.
I stay available to gather other thing that could be necessary for debug.

**Comment by mzilyas-syna** [comment]
I have exactly the same issue but with Prometheus datasource. If I switch to influxdb datasource there is no timeout and all renders succeed.

From what I have found it looks like a Grafana proxy problem, if I change the datasource type from proxy to direct, all renders work again. 

That is why I posted my issue with grafana main project: https://github.com/grafana/grafana/issues/113458

**Comment by mzilyas-syna** [comment]
Fixed!
When composing the render url,  you need to have all your dashboard variables mentioned with a value. In my case there was one variable not mentioned and that created this random behaviour of some panels being rendered and others went into timeout.

Tip: generate a png using the grafana webui. Click on the three dots from a specific panel -> Share -> Share link -> Generate image
And capture the url with your browser. See what is missing from the url you are using.

Quite some time went into investigating this, can this failure if providing all variables be an error log??

**Comment by macabu** [comment]
We've made some fixes in Grafana to properly propagate query variables and our internal monitoring shows promising results in the stability of panel screenshots!
For on-prem, it should be released in the following versions: 13.0.0, 12.4.3, 12.3.7, 12.2.9 and 11.6.15
Give it a try when these release, paired with a recent version of the Image Renderer, and let us know in case you still have issues.
